/*
 * Ò»¼üµÇÂ¼.java
 *
 * Created on __DATE__, __TIME__
 */

package View;

import javax.swing.ImageIcon;

/**
 *
 * @author  __USER__
 */
public class Ò»¼üµÇÂ¼ extends javax.swing.JFrame {

	/** Creates new form Ò»¼üµÇÂ¼ */
	public Ò»¼üµÇÂ¼() {
		initComponents();
		this.setIconImage(new ImageIcon("D:/java³ÌÐòÊµÑµ/dodada/src/Í¼/logoÉîÀ¶.jpg").getImage());
		this.setVisible(true);
		this.setLocationRelativeTo(null);
		//this.dispose();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/Ð¡Í·Ïñ.jpg"))); // NOI18N

		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/¶þÎ¬Âë.jpg"))); // NOI18N

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel1Layout.createSequentialGroup().addGap(211, 211, 211)
						.addComponent(jLabel2,
								javax.swing.GroupLayout.PREFERRED_SIZE, 130,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(217, Short.MAX_VALUE)).addGroup(
				jPanel1Layout.createParallelGroup(
						javax.swing.GroupLayout.Alignment.LEADING).addGroup(
						jPanel1Layout.createSequentialGroup()
								.addGap(19, 19, 19).addComponent(jLabel1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										520,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(19, Short.MAX_VALUE))));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel1Layout.createSequentialGroup().addGap(211, 211, 211)
						.addComponent(jLabel2,
								javax.swing.GroupLayout.PREFERRED_SIZE, 105,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(249, Short.MAX_VALUE)).addGroup(
				jPanel1Layout.createParallelGroup(
						javax.swing.GroupLayout.Alignment.LEADING).addGroup(
						jPanel1Layout.createSequentialGroup()
								.addGap(20, 20, 20).addComponent(jLabel1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										525,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(20, Short.MAX_VALUE))));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addComponent(jPanel1,
						javax.swing.GroupLayout.PREFERRED_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(28, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addComponent(jPanel1,
						javax.swing.GroupLayout.PREFERRED_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(30, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		
		Ò»¼üµÇÂ¼ frame = new Ò»¼üµÇÂ¼();
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Ò»¼üµÇÂ¼().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel1;
	// End of variables declaration//GEN-END:variables

}