/*
 * 导航.java
 *
 * Created on __DATE__, __TIME__
 */

package View;

import java.io.IOException;
import java.net.UnknownHostException;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import model.User;

/**
 *
 * @author  __USER__
 */   
public class 导航 extends javax.swing.JFrame {
        
	/** Creates new form 导航 */
	
	private static User u ;
	public 导航(User u) {
		this.setIconImage(new ImageIcon("D:/java程序实训/dodada/src/图/logo深蓝.jpg")
				.getImage());
		initComponents();
		this.setVisible(true);
		导航.u=u;
		this.setLocationRelativeTo(null);
		this.dispose();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jTabbedPane1 = new javax.swing.JTabbedPane();
		jPanel1 = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jButton5 = new javax.swing.JButton();
		jButton6 = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jButton19 = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();
		jButton7 = new javax.swing.JButton();
		jLabel7 = new javax.swing.JLabel();
		jButton10 = new javax.swing.JButton();
		jLabel10 = new javax.swing.JLabel();
		jButton12 = new javax.swing.JButton();
		jLabel12 = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();
		jButton13 = new javax.swing.JButton();
		jPanel3 = new javax.swing.JPanel();
		jButton8 = new javax.swing.JButton();
		jLabel8 = new javax.swing.JLabel();
		jButton14 = new javax.swing.JButton();
		jButton15 = new javax.swing.JButton();
		jButton16 = new javax.swing.JButton();
		jLabel14 = new javax.swing.JLabel();
		jLabel15 = new javax.swing.JLabel();
		jLabel16 = new javax.swing.JLabel();
		jPanel4 = new javax.swing.JPanel();
		jButton9 = new javax.swing.JButton();
		jLabel9 = new javax.swing.JLabel();
		jButton11 = new javax.swing.JButton();
		jLabel11 = new javax.swing.JLabel();
		jLabel17 = new javax.swing.JLabel();
		jButton17 = new javax.swing.JButton();
		jButton18 = new javax.swing.JButton();
		jLabel18 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(0, 102, 153));

		jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/图/英雄联盟.jpg"))); // NOI18N
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 20));
		jLabel1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel1.setText("\u82f1\u96c4\u8054\u76df");

		jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/图/魔兽世界.jpg"))); // NOI18N
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/图/穿越火线.jpg"))); // NOI18N
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/图/地下城勇士.jpg"))); // NOI18N
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/图/刀剑神域.jpg"))); // NOI18N
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});

		jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/图/守望先锋.png"))); // NOI18N
		jButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton6ActionPerformed(evt);
			}
		});

		jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 20));
		jLabel2.setForeground(new java.awt.Color(255, 255, 255));
		jLabel2.setText("\u9b54\u517d\u4e16\u754c");

		jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 20));
		jLabel3.setForeground(new java.awt.Color(255, 255, 255));
		jLabel3.setText("\u7a7f\u8d8a\u706b\u7ebf");

		jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 20));
		jLabel4.setForeground(new java.awt.Color(255, 255, 255));
		jLabel4.setText("\u5730\u4e0b\u57ce\u52c7\u58eb");

		jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 20));
		jLabel5.setForeground(new java.awt.Color(255, 255, 255));
		jLabel5.setText("\u5200\u5251\u795e\u57df");

		jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 20));
		jLabel6.setForeground(new java.awt.Color(255, 255, 255));
		jLabel6.setText("\u5b88\u671b\u5148\u950b");

		jButton19.setBackground(new java.awt.Color(0, 153, 204));
		jButton19.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jButton19.setForeground(new java.awt.Color(255, 255, 255));
		jButton19.setText("\u9996\u9875");
		jButton19.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton19ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(70, 70, 70)
										.addComponent(
												jLabel4,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												112,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(195, 195, 195)
										.addComponent(
												jLabel5,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												94,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												214, Short.MAX_VALUE)
										.addComponent(
												jLabel6,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												94,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(79, 79, 79))
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(
																				74,
																				74,
																				74)
																		.addComponent(
																				jLabel1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				94,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				209,
																				209,
																				209)
																		.addComponent(
																				jLabel2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				94,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																jPanel1Layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								false)
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								jPanel1Layout
																										.createSequentialGroup()
																										.addComponent(
																												jButton4,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												223,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												Short.MAX_VALUE)
																										.addComponent(
																												jButton5,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												223,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								jPanel1Layout
																										.createSequentialGroup()
																										.addComponent(
																												jButton1,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												223,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addGap(
																												72,
																												72,
																												72)
																										.addComponent(
																												jButton2,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												223,
																												javax.swing.GroupLayout.PREFERRED_SIZE)))))
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(
																				72,
																				72,
																				72)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								jButton6,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								223,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton3,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								223,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addContainerGap())
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel1Layout
																		.createSequentialGroup()
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				150,
																				Short.MAX_VALUE)
																		.addComponent(
																				jLabel3,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				94,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				81,
																				81,
																				81))))
						.addGroup(
								jPanel1Layout.createSequentialGroup().addGap(
										159, 159, 159).addComponent(jButton19,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										495, Short.MAX_VALUE).addGap(204, 204,
										204)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jButton2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				121,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel2))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jButton3,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				121,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel3))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jButton1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				121,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel1)))
										.addGap(50, 50, 50)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																jButton4,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																121,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jButton5,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																121,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jButton6,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																121,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel5)
														.addComponent(jLabel4)
														.addComponent(jLabel6))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												12, Short.MAX_VALUE)
										.addComponent(jButton19)
										.addContainerGap()));

		jTabbedPane1.addTab("\u70ed\u95e8\u6e38\u620f", jPanel1);

		jPanel2.setBackground(new java.awt.Color(0, 102, 153));

		jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/图/英雄联盟.jpg"))); // NOI18N
		jButton7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton7ActionPerformed(evt);
			}
		});

		jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 20));
		jLabel7.setForeground(new java.awt.Color(255, 255, 255));
		jLabel7.setText("\u82f1\u96c4\u8054\u76df");

		jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/图/穿越火线.jpg"))); // NOI18N
		jButton10.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton10ActionPerformed(evt);
			}
		});

		jLabel10.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 20));
		jLabel10.setForeground(new java.awt.Color(255, 255, 255));
		jLabel10.setText("\u7a7f\u8d8a\u706b\u7ebf");

		jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/战地5.jpg"))); // NOI18N
		jButton12.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton12ActionPerformed(evt);
			}
		});

		jLabel12.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 20));
		jLabel12.setForeground(new java.awt.Color(255, 255, 255));
		jLabel12.setText("\u6218\u57305");

		jLabel13.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 20));
		jLabel13.setForeground(new java.awt.Color(255, 255, 255));
		jLabel13.setText("\u771f\u4e09\u56fd\u65e0\u53cc");

		jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/真三国无双.jpg"))); // NOI18N
		jButton13.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton13ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addGap(
																				94,
																				94,
																				94)
																		.addComponent(
																				jLabel7,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				94,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				275,
																				275,
																				275)
																		.addComponent(
																				jLabel10,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				94,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel2Layout
																										.createSequentialGroup()
																										.addGap(
																												102,
																												102,
																												102)
																										.addComponent(
																												jLabel12,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												94,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addGroup(
																								jPanel2Layout
																										.createSequentialGroup()
																										.addGap(
																												43,
																												43,
																												43)
																										.addGroup(
																												jPanel2Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																jButton12,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																223,
																																javax.swing.GroupLayout.PREFERRED_SIZE)
																														.addComponent(
																																jButton7,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																223,
																																javax.swing.GroupLayout.PREFERRED_SIZE))))
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel2Layout
																										.createSequentialGroup()
																										.addGap(
																												134,
																												134,
																												134)
																										.addGroup(
																												jPanel2Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																jButton13,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																223,
																																javax.swing.GroupLayout.PREFERRED_SIZE)
																														.addComponent(
																																jButton10,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																223,
																																javax.swing.GroupLayout.PREFERRED_SIZE)))
																						.addGroup(
																								jPanel2Layout
																										.createSequentialGroup()
																										.addGap(
																												195,
																												195,
																												195)
																										.addComponent(
																												jLabel13,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												108,
																												javax.swing.GroupLayout.PREFERRED_SIZE)))))
										.addContainerGap(235, Short.MAX_VALUE)));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addGap(44, 44, 44)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																jButton7,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																121,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jButton10,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																121,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel7)
														.addComponent(jLabel10))
										.addGap(45, 45, 45)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jButton12,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																121,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jButton13,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																121,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel12)
														.addComponent(jLabel13))
										.addContainerGap(46, Short.MAX_VALUE)));

		jTabbedPane1.addTab("\u6218\u4e89", jPanel2);

		jPanel3.setBackground(new java.awt.Color(0, 102, 153));

		jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/图/魔兽世界.jpg"))); // NOI18N
		jButton8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton8ActionPerformed(evt);
			}
		});

		jLabel8.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 20));
		jLabel8.setForeground(new java.awt.Color(255, 255, 255));
		jLabel8.setText("\u9b54\u517d\u4e16\u754c");

		jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/毁灭战士.jpg"))); // NOI18N
		jButton14.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton14ActionPerformed(evt);
			}
		});

		jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/僵尸警戒.png"))); // NOI18N
		jButton15.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton15ActionPerformed(evt);
			}
		});

		jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/隐藏之谜15：灵异高校.jpg"))); // NOI18N
		jButton16.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton16ActionPerformed(evt);
			}
		});

		jLabel14.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 20));
		jLabel14.setForeground(new java.awt.Color(255, 255, 255));
		jLabel14.setText("\u6bc1\u706d\u6218\u58eb");

		jLabel15.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 20));
		jLabel15.setForeground(new java.awt.Color(255, 255, 255));
		jLabel15.setText("\u50f5\u5c38\u8b66\u6212");

		jLabel16.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 20));
		jLabel16.setForeground(new java.awt.Color(255, 255, 255));
		jLabel16
				.setText("\u9690\u85cf\u4e4b\u8c1c15\uff1a\u7075\u5f02\u6821\u56ed");

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout
				.setHorizontalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addGap(
																				113,
																				113,
																				113)
																		.addComponent(
																				jLabel8,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				94,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				251,
																				251,
																				251)
																		.addComponent(
																				jLabel14,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				94,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel3Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel3Layout
																										.createSequentialGroup()
																										.addGap(
																												46,
																												46,
																												46)
																										.addGroup(
																												jPanel3Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.TRAILING)
																														.addComponent(
																																jButton8,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																223,
																																javax.swing.GroupLayout.PREFERRED_SIZE)
																														.addComponent(
																																jButton15,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																223,
																																javax.swing.GroupLayout.PREFERRED_SIZE)))
																						.addGroup(
																								jPanel3Layout
																										.createSequentialGroup()
																										.addGap(
																												109,
																												109,
																												109)
																										.addComponent(
																												jLabel15,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												94,
																												javax.swing.GroupLayout.PREFERRED_SIZE)))
																		.addGap(
																				117,
																				117,
																				117)
																		.addGroup(
																				jPanel3Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								jButton16,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								223,
																								Short.MAX_VALUE)
																						.addComponent(
																								jButton14,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								223,
																								Short.MAX_VALUE)
																						.addComponent(
																								jLabel16,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE))))
										.addContainerGap(249, Short.MAX_VALUE)));
		jPanel3Layout
				.setVerticalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addGap(46, 46, 46)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																jButton14,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																121,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jButton8,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																121,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel14)
														.addComponent(jLabel8))
										.addGap(18, 18, 18)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jButton16,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																121,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jButton15,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																121,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel15)
														.addComponent(jLabel16))
										.addContainerGap(71, Short.MAX_VALUE)));

		jTabbedPane1.addTab("\u6050\u6016", jPanel3);

		jPanel4.setBackground(new java.awt.Color(0, 102, 153));

		jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/图/守望先锋.png"))); // NOI18N
		jButton9.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton9ActionPerformed(evt);
			}
		});

		jLabel9.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 20));
		jLabel9.setForeground(new java.awt.Color(255, 255, 255));
		jLabel9.setText("\u5b88\u671b\u5148\u950b");

		jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/图/刀剑神域.jpg"))); // NOI18N
		jButton11.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton11ActionPerformed(evt);
			}
		});

		jLabel11.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 20));
		jLabel11.setForeground(new java.awt.Color(255, 255, 255));
		jLabel11.setText("\u5200\u5251\u795e\u57df");

		jLabel17.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 20));
		jLabel17.setForeground(new java.awt.Color(255, 255, 255));
		jLabel17.setText("\u7cbe\u7075\u5b9d\u53ef\u68a6");

		jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/精灵宝可梦.jpg"))); // NOI18N
		jButton17.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton17ActionPerformed(evt);
			}
		});

		jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/我的世界.PNG"))); // NOI18N
		jButton18.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton18ActionPerformed(evt);
			}
		});

		jLabel18.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 20));
		jLabel18.setForeground(new java.awt.Color(255, 255, 255));
		jLabel18.setText("\u6211\u7684\u4e16\u754c");

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(
				jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout
				.setHorizontalGroup(jPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel4Layout
										.createSequentialGroup()
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel4Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel4Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel4Layout
																										.createSequentialGroup()
																										.addGap(
																												96,
																												96,
																												96)
																										.addComponent(
																												jLabel17,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												119,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addGroup(
																								jPanel4Layout
																										.createSequentialGroup()
																										.addGap(
																												106,
																												106,
																												106)
																										.addComponent(
																												jLabel9,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												94,
																												javax.swing.GroupLayout.PREFERRED_SIZE)))
																		.addGap(
																				4,
																				4,
																				4)
																		.addGroup(
																				jPanel4Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel4Layout
																										.createSequentialGroup()
																										.addGap(
																												251,
																												251,
																												251)
																										.addComponent(
																												jLabel18,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												94,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addGroup(
																								jPanel4Layout
																										.createSequentialGroup()
																										.addGap(
																												259,
																												259,
																												259)
																										.addComponent(
																												jLabel11,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												94,
																												javax.swing.GroupLayout.PREFERRED_SIZE))))
														.addGroup(
																jPanel4Layout
																		.createSequentialGroup()
																		.addGap(
																				42,
																				42,
																				42)
																		.addGroup(
																				jPanel4Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								jButton9,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								223,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton17,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								223,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGap(
																				135,
																				135,
																				135)
																		.addGroup(
																				jPanel4Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jButton11,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								223,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton18,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								223,
																								javax.swing.GroupLayout.PREFERRED_SIZE))))
										.addContainerGap(235, Short.MAX_VALUE)));
		jPanel4Layout
				.setVerticalGroup(jPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel4Layout
										.createSequentialGroup()
										.addGap(44, 44, 44)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel4Layout
																		.createSequentialGroup()
																		.addComponent(
																				jButton11,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				121,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel11))
														.addGroup(
																jPanel4Layout
																		.createSequentialGroup()
																		.addComponent(
																				jButton9,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				121,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel9)))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												31, Short.MAX_VALUE)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																jButton18,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																121,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jButton17,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																121,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel17)
														.addComponent(jLabel18))
										.addGap(60, 60, 60)));

		jTabbedPane1.addTab("\u4f11\u95f2", jPanel4);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 863,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addComponent(jTabbedPane1,
						javax.swing.GroupLayout.PREFERRED_SIZE, 483,
						javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {
		new Shouye(null).setVisible(true);
		this.dispose();
	}

	private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {
		JOptionPane.showMessageDialog(this, "未开发");
	}

	private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {
		JOptionPane.showMessageDialog(this, "未开发");
	}

	private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {
		if (evt.getSource() == jButton11) {
			this.dispose();//点击按钮时frame1销毁,new一个frame2
			new 支付1();
		}
	}

	private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {
		if (evt.getSource() == jButton9) {
			this.dispose();//点击按钮时frame1销毁,new一个frame2
			try {
				new 支付6(u);
			} catch (UnknownHostException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
	}

	private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {
		JOptionPane.showMessageDialog(this, "未开发");
	}

	private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {
		JOptionPane.showMessageDialog(this, "未开发");
	}

	private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {
		if (evt.getSource() == jButton8) {
			this.dispose();//点击按钮时frame1销毁,new一个frame2
			new 支付3();
		}
	}

	private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {
		JOptionPane.showMessageDialog(this, "未开发");
	}

	private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {
		JOptionPane.showMessageDialog(this, "未开发");
	}

	private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {
		if (evt.getSource() == jButton10) {
			this.dispose();//点击按钮时frame1销毁,new一个frame2
			new 支付4();
		}
	}

	private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {
		if (evt.getSource() == jButton7) {
			this.dispose();//点击按钮时frame1销毁,new一个frame2
			new 支付2();
		}
	}

	private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
		if (evt.getSource() == jButton2) {
			this.dispose();//点击按钮时frame1销毁,new一个frame2
			try {
				new 支付6(u);
			} catch (UnknownHostException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}}


	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
		if (evt.getSource() == jButton5) {
			this.dispose();//点击按钮时frame1销毁,new一个frame2
			new 支付1();
		}
	}

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		JOptionPane.showMessageDialog(this, "未开发");
	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		if (evt.getSource() == jButton3) {
			this.dispose();//点击按钮时frame1销毁,new一个frame2
			new 支付4();
		}
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		if (evt.getSource() == jButton2) {
			this.dispose();//点击按钮时frame1销毁,new一个frame2
			new 支付3();
		}
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		if (evt.getSource() == jButton1) {
			this.dispose();//点击按钮时frame1销毁,new一个frame2
			new 支付2();
		}
	}

	private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {
		JOptionPane.showMessageDialog(this, "未开发");
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		导航 frame = new 导航(u);
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new 导航(u).setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton10;
	private javax.swing.JButton jButton11;
	private javax.swing.JButton jButton12;
	private javax.swing.JButton jButton13;
	private javax.swing.JButton jButton14;
	private javax.swing.JButton jButton15;
	private javax.swing.JButton jButton16;
	private javax.swing.JButton jButton17;
	private javax.swing.JButton jButton18;
	private javax.swing.JButton jButton19;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton7;
	private javax.swing.JButton jButton8;
	private javax.swing.JButton jButton9;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel18;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JTabbedPane jTabbedPane1;
	// End of variables declaration//GEN-END:variables

}